import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  display: 'swap',
  src: './fonts/satoshi.ttf',
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: "a17 - Framer Ecommerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} font-satoshi antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
