import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/homepage/Navbar";
import Footer from "@/components/homepage/Footer";
import SubscribeCard from "@/components/homepage/SubscribeCard";

const satoshi = localFont({
  display: 'swap',
  src: '../../public/fonts/satoshi.ttf',
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: "A17 - Framer Ecommerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} font-satoshi antialiased bg-white`}
      >
        <Navbar />
        {children}
        <SubscribeCard />
        <Footer />
      </body>
    </html>
  );
}
